# -*- coding: utf-8 -*-
"""Simple Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13iMeXQcJI7lZRhIWAUSxCSw7cXnUwCwR
"""

# Simple calculator with function
def calculator():
    while True:
        decision = input("Do you want to continue (yes/no): ")
        if decision.lower() == "no":
            break

        num1 = int(input("Enter first value: "))
        num2 = int(input("Enter second value: "))
        operator = input("Enter operator you want to perform (+, -, *, /): ")

        if operator == "+":
            print("Result is:", num1 + num2)
        elif operator == "-":
            print("Result is:", num1 - num2)
        elif operator == "*":
            print("Result is:", num1 * num2)
        elif operator == "/":
            if num2 != 0:
                print("Result is:", num1 / num2)
            else:
                print("You can't divide by 0!")
        else:
            print("Invalid operator!")